### ISSUE TITLE
Issue in Parsing big files

### ISSUE THREAD

**Issue by dheeraj12190** [Maximus5/RapidXml#1]
Hi, 
I am using rapidxml in my project. it is working fine with small files but once the file size increases more then 65KB then searching first node gives segmentation fault error

**Comment by Maximus5** [comment]
I'm not an author of this library, sorry.

**Comment by Maximus5** [comment]
BTW, my current ConEmu.xml is about 120KB.

**Comment by Maximus5** [comment]
Anyway, if you find the problem, PR is appreciated
